apiVersion: v1
kind: Service
metadata:
  name: explora-kafka
  labels:
    app: explora-kafka
spec:
  type: LoadBalancer
  ports:
   - port: 7070
     targetPort: 7070
     nodePort: 30070
  selector:
   app: explora-kafka